### ISSUE TITLE
Seems to be not respecting ignored paths

### ISSUE THREAD

**Issue by jbeker** [jsmecham/nova-rubocop#10]
First, thank you so much for writing this and if I can help test, I am happy to.

I am seeing errors reported for files that should be excluded in the `.rubocop.yml` file. I ran into this before with other tools and I believe the solution was to add the `--force-exclusion` when running `rubocop`.

Might that be an option? Or even the default?

**Comment by jbeker** [comment]
Hmm, reading the code I see you are passing the file data on STDIN. That makes this more complicated...

**Comment by jbeker** [comment]
Maybe this option:

```
-s, --stdin FILE                 Pipe source from STDIN, using FILE in offense
                                           reports. This is useful for editor integration.
```

This seems to imply it will use that path name for includes/excludes: https://github.com/rubocop-hq/rubocop/blob/dfdf8f924d5f47da03dfb0a7bc48a2690661f329/lib/rubocop/options.rb#L13-L16

**Comment by jsmecham** [comment]
Yea, it's important to use `STDIN` because we want to be able to start reporting on errors before the file is saved.
