### ISSUE TITLE
RuboCop Errors Are Not Debuggable Due to Lack of Console Output

### ISSUE THREAD

**Issue by HunterHillegas** [jsmecham/nova-rubocop#5]
Well, it was working for awhile but it suddenly stopped. In the extensions console, I see this:

RuboCop[10:15:45.408000] Found RuboCop 0.80.1 (Global)
RuboCop[10:15:45.415000] env: rubocop: No such file or directory

... and that's it - nothing is showing in the editor even when I make a known error.

I've been using RuboCop long enough to know that sometimes it breaks with all the different versions of Ruby, etc... But this info above is not enough to debug.

I can't tell which Ruby it's using (I use RVM) or why it's failing. When I run from the command line, RuboCop works fine, is in the Gemfile, installed, etc...

Is it possible for the extension to do what other extensions in editors like Sublime do and print out all of the details about what they are running so that errors are debuggable?

**Comment by HunterHillegas** [comment]
Digging into this a bit more and found the Help.md file which has info on where it looks for Rubocop.

This is a Rails project so I've got a Gemfile that includes the gem and running `bundle exec rubocop` does work which is why I can't figure out why the extension can't find what it needs.

Going to try to figure out if there's a way to run the thing in Nova as a development extension to see if that helps me figure it out.

**Comment by jsmecham** [comment]
I just released an update to the extension (v0.4.0) that might fix the issue you were seeing, due to a bug in the bundled RuboCop check. Could you try again with v0.4.0 and let me know if you are still seeing this? Thanks!

**Comment by jsmecham** [comment]
Actually, released another update that probably most likely fixes this issue. Give v0.4.2 a try, please, and feel free to reopen this issue if it is still broken. Thanks!

**Comment by HunterHillegas** [comment]
Thanks, I was gonna say that 0.4.0 did not resolve it.

I just updated and now I'm seeing this:

`RuboCop[13:44:37.251000] Extension encountered an uncaught exception:
/Users/hunter/Library/Application Support/Nova/Extensions/Mecham.RuboCop/Scripts/main.dist.js (Line 180, Column 0)
SyntaxError: JSON Parse error: Unexpected identifier "The"
    parse@[native code]
    handleOutput@file:///Users/hunter/Library/Application%20Support/Nova/Extensions/Mecham.RuboCop/Scripts/main.dist.js:180:40
    file:///Users/hunter/Library/Application%20Support/Nova/Extensions/Mecham.RuboCop/Scripts/main.dist.js:161:71`

That's after just about 10 seconds of testing though. I'll keep looking into it.

**Comment by HunterHillegas** [comment]
@jsmecham Looks like it's not giving me an option to re-open the issue, FYI.

**Comment by jsmecham** [comment]
I think I know what's up, will have a release later this evening to fix.

**Comment by HunterHillegas** [comment]
Looks like a similar error but in case helpful, also seeing this:

`RuboCop[8:17:02.042000] Extension encountered an uncaught exception:
/Users/hunter/Library/Application Support/Nova/Extensions/Mecham.RuboCop/Scripts/main.dist.js (Line 180, Column 0)
SyntaxError: JSON Parse error: Unexpected identifier "Warning"
    parse@[native code]
    handleOutput@file:///Users/hunter/Library/Application%20Support/Nova/Extensions/Mecham.RuboCop/Scripts/main.dist.js:180:40
    file:///Users/hunter/Library/Application%20Support/Nova/Extensions/Mecham.RuboCop/Scripts/main.dist.js:161:71
`

**Comment by jsmecham** [comment]
I have a fix in my local environment, I’ll cut a release this morning.

**Comment by jsmecham** [comment]
Just published v0.5.0, could you give that a try?

**Comment by HunterHillegas** [comment]
@jsmecham Yes, whatever you changed resolved the issue - RuboCop is now recognized and the linting results are visible inside Nova again. Nice! Thanks for the extension BTW.

**Comment by jsmecham** [comment]
Thanks for the feedback!
